feat: createContext / useReducer
bogdaryan/react-stellar-burger pull request #3
Opened 2023-11-23 12:55 UTC by bogdaryan

2023-12-01 16:39 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Используется redux;

### **Но есть несколько замечаний, которые нужно исправить:**

- Не реализован функционал с Drag and Drop. А также советую ещё раз внимательно ознакомиться с чек-листом.

- Нужно убрать функционал добавления ингредиентов по клику.

- В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/NUQGFc52wGDjsg>. Вам нужно передавать не объект а `id` ингредиентов;

- По чек-листу требуется реализовать :

  - При скролле внутри компонента BurgerIngredients самый ближний к верхней левой границе заголовок контейнера должен становится активным;

  - Для каждого экшена, который связан с запросом к Api создан усилитель. Для таких экшенов описан тип \_REQUEST, тип \_SUCCESS, \_ERROR

  - Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента приводится к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-12-01 16:39 UTC, ArslanMustafin commented on src/asyncActions/postOrder.js
> +      });
**Надо исправить:**

здесь и далее.

Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента приводится к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.

2023-12-01 16:39 UTC, ArslanMustafin commented on src/asyncActions/postOrder.js
> +      })
**Надо исправить:**

Здесь и далее. В других запросах.

 Для каждого экшена, который связан с запросом к Api должен быть создан усилитель. Для таких экшенов описан тип \_REQUEST, тип \_SUCCESS, \_ERROR

2023-12-01 16:39 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
>        gap;
**Надо исправить:**

Немного не понимаю зачем вам это.

2023-12-01 16:39 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +  }, [bun, ingredients]);
**Можно лучше:**

totalPrice лучше считать, используя, `useMemo`

2023-12-01 16:39 UTC, ArslanMustafin commented on src/components/burger-ingredients/ingredient/ingredient.jsx
> +      }}
**Надо исправить:**

Нужно вынести обработчик событий в функцию. А также убрать функционал добавления ингредиента.

2023-12-01 16:39 UTC, ArslanMustafin commented on src/services/ingredientsSlice.js
> +  },
**Можно лучше:**

хорошей практикой является выносить начальный стейт в переменную.

2023-12-05 13:01 UTC, bogdaryan commented
Дедлайн уже рядом, нужно ревью, пока я думаю, как сделать сортировку внутри конструктора

2023-12-05 13:11 UTC, ArslanMustafin commented
> Дедлайн уже рядом, нужно ревью, пока я думаю, как сделать сортировку внутри конструктора

Добрый день, лучше реализуйте полностью функционал, так меньше шансов того, что работа снова будет не принята)). Если вам нужна помощь, то смело обращайтесь к наставнику.

2023-12-06 06:44 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

### **Вы молодец!**

- Большинство замечаний было исправлено;

### **Но есть несколько замечаний, которые нужно исправить:**

- Не работает DnD для ингредиентов.

- Отметил замечания в коде.

2023-12-06 06:44 UTC, ArslanMustafin commented on src/components/burger-constructor/ingredients-list/ingredients-list.jsx
> +  }, []);
**Надо исправить:**

здесь не должно быть `useCallback`. Выводите элементы сразу в jsx, тут нет дополнительного функционала, и отделять что-то не нужно))

2023-12-06 06:44 UTC, ArslanMustafin commented on src/components/burger-constructor/ingredients-list/ingredients-list.jsx
> +          handleClose={() => dispatch(deleteIngredient(_key))}
**Можно лучше:**

а вот эту функцию можно вынести в `useCallback`))

2023-12-06 06:44 UTC, ArslanMustafin commented on src/components/burger-constructor/ingredients-list/ingredients-list.jsx
> +        _key: nanoid(),
**Надо исправить:**

генерировать `id` лучше в самом экшене, чтобы потом было удобнее переиспользовать, а не копипастить код

2023-12-06 06:44 UTC, ArslanMustafin commented on src/components/burger-constructor/ingredients-list/ingredients-list.jsx
> +        style={{ maxHeight: 300 }}
**Надо исправить:**

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2023-12-06 06:44 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
>    });
**Надо исправить:**

Здесь не должно быть `useEffect`, без зависимостей.  Это очень сильно вредит производительности приложения.

Рекомендую почитать про библиотеку `react-intersection-observer`

2023-12-06 06:44 UTC, ArslanMustafin commented on src/components/burger-ingredients/ingredient/ingredient.jsx
> +  });
**Надо исправить:**

Тут не нужно использовать `useEffect`. И это не очень правильно когда при любом ререндере компонента происходит данный экшен. 

Подписываться на события DnD нужно не через `useEffect`, обратитесь за помощью к наставнику.

2023-12-09 06:47 UTC, merged